#Load libraries
```{r}
library(readxl)
library(forcats) 
library(tidyr)  
library(dplyr)  
library(ggsignif)
library(ggplot2)
library(broom) 
library(rstatix)
library(ggpubr)
library(stringr)
library(viridis)
library(emmeans)
library(purrr)
library(car)
library(extrafont)
library(plotrix)
library(FSA) 
library(ggpubr) 
library(drc)
library(eulerr)
library(clusterProfiler)
library(enrichplot)
library(org.Mm.eg.db)
library(KEGGREST)
library(readr)
library(ggrepel)
```

#KEGG Plots
```{r}

files <- list.files(path = "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/invivo-pfas-immunotox/Eunnara stuff/KEGG_results/", pattern = "*.csv", full.names = TRUE)

read_with_group <- function(file) {
  df <- read_csv(file)
  df$group <- tools::file_path_sans_ext(basename(file))  
  return(df)
}


all_kegg <- lapply(files, read_with_group) %>%
  bind_rows()

all_kegg <- all_kegg %>%
  mutate(qvalue = as.numeric(qvalue),
         Count = as.numeric(Count),
         Description = str_trunc(Description, 50))
group_order <- c(
  "KEGG_results_PFOA_Female_28-day",
  "KEGG_results_PFOS_Female_28-day",
  "KEGG_results_PFOA_Male_28-day",
  "KEGG_results_PFOS_Male_28-day",
  "KEGG_results_PFOA_Female_56-day",
  "KEGG_results_PFOS_Female_56-day",
  "KEGG_results_PFOA_Male_56-day",
  "KEGG_results_PFOS_Male_56-day"
)
rownames(all_kegg$group)
top_kegg <- all_kegg %>%
  group_by(group) %>%
  arrange(qvalue) %>%
  slice_head(n = 10) %>%
  ungroup()

top_kegg$group <- factor(top_kegg$group, levels = group_order)

top_pathways <- top_kegg %>%
  distinct(Description) %>%
  pull(Description)

plot_kegg <- all_kegg %>%
  filter(Description %in% top_pathways, qvalue < 0.05)

plot_kegg <- plot_kegg %>%
  left_join(
    top_kegg %>% 
      dplyr::select(group, Description) %>%
      mutate(in_top10 = TRUE),
    by = c("group", "Description")
  ) %>%
  mutate(in_top10 = ifelse(is.na(in_top10), FALSE, TRUE))

plot_kegg <- plot_kegg %>%
  mutate(logq = -log10(qvalue + 1e-10))  
plot_kegg$group <- factor(plot_kegg$group, levels = group_order)
kegg_plot <- ggplot(plot_kegg, aes(x = group, y = fct_reorder(Description, Count))) +
  geom_point(aes(size = Count, color = logq, shape = in_top10)) +
  
  scale_shape_manual(
    values = c(`TRUE` = 16, `FALSE` = 1),
    labels = c("Other significant", "Top 10 in group"),
    name = "Pathway status"
  ) +
  scale_color_viridis_c(
    option = "plasma",
    name = expression(-log[10](qvalue))
  ) +
  scale_size_continuous(name = "Gene Count") +
  labs(
    x = "Group",
    y = "KEGG Pathway",
    title = "KEGG Pathways: Top 10 and Other Significant Occurrences"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5)
  )

print(kegg_plot)


ggsave(filename = "../invivo-pfas-immunotox/R input 56d/plots/kegg_top10_vs_all.png",
       plot = kegg_plot, width = 12, height = 6, dpi = 300, bg = "white")



```

#Kegg overlap
```{r}
#Load in Kegg data with non sig pathways
files <- list.files(path = "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/invivo-pfas-immunotox/Eunnara stuff/KEGG_results_all//", pattern = "*.csv", full.names = TRUE)

read_with_group <- function(file) {
  df <- read_csv(file)
  df$group <- tools::file_path_sans_ext(basename(file))  
  return(df)
}


all_kegg <- lapply(files, read_with_group) %>%
  bind_rows()

all_kegg <- all_kegg %>%
  mutate(qvalue = as.numeric(qvalue),
         Count = as.numeric(Count),
         Description = str_trunc(Description, 50))
group_order <- c(
  "KEGG_results_PFOA_Female_28-day",
  "KEGG_results_PFOS_Female_28-day",
  "KEGG_results_PFOA_Male_28-day",
  "KEGG_results_PFOS_Male_28-day",
  "KEGG_results_PFOA_Female_56-day",
  "KEGG_results_PFOS_Female_56-day",
  "KEGG_results_PFOA_Male_56-day",
  "KEGG_results_PFOS_Male_56-day"
)
rownames(all_kegg$group)
all_kegg <- all_kegg %>%
  extract(group, into = c("prefix", "PFAS", "Sex", "Time"),
          regex = "^(KEGG_results)_(\\w+)_(Female|Male)_(\\d+-day)$",
          remove = FALSE) %>%
  mutate(Time = gsub("-day", "", Time))
```

##Sex
```{r}
female_df <- all_kegg %>% filter(Sex == "Female")
male_df   <- all_kegg %>% filter(Sex == "Male")

merged_sex <- inner_join(
  female_df %>% group_by(Description) %>% summarize(qvalue_female = min(qvalue)),
  male_df   %>% group_by(Description) %>% summarize(qvalue_male = min(qvalue)),
  by = "Description"
) %>%
  mutate(
    log_female = log10(qvalue_female),
    log_male   = log10(qvalue_male),
    diff = log_female - log_male
  )

# 2. Identify labels

# Near-diagonal
merged_sex <- merged_sex %>%
  mutate(label_near_diag = ifelse(abs(diff) < 0.5, Description, NA))

top_female <- merged_sex %>%
  filter(qvalue_male > 0.05) %>%
  arrange(qvalue_female) %>%
  slice_head(n = 2) %>%
  pull(Description)

merged_sex <- merged_sex %>%
  mutate(label_female_specific = ifelse(Description %in% top_female, Description, NA))

top_male <- merged_sex %>%
  filter(qvalue_female > 0.05) %>%
  arrange(qvalue_male) %>%
  slice_head(n = 2) %>%
  pull(Description)

merged_sex <- merged_sex %>%
  mutate(label_male_specific = ifelse(Description %in% top_male, Description, NA))

# Top 5 shared (significant in both sexes)
shared_top5 <- merged_sex %>%
  filter(qvalue_female <= 0.05, qvalue_male <= 0.05) %>%
  mutate(mean_q = (qvalue_female + qvalue_male) / 2) %>%
  arrange(mean_q) %>%
  slice_head(n = 5) %>%
  pull(Description)

merged_sex <- merged_sex %>%
  mutate(label_shared = ifelse(Description %in% shared_top5, Description, NA))

# Combine labels & colors
merged_sex <- merged_sex %>%
  mutate(
    label_combined = coalesce(
      label_shared,
      label_female_specific,
      label_male_specific,
    ),
    label_color = case_when(
      !is.na(label_shared)          ~ "purple",
      !is.na(label_female_specific) ~ "red",
      !is.na(label_male_specific)   ~ "blue",
      TRUE                          ~ "grey80"
    ),
    sig = case_when(
  qvalue_female <= 0.05 & qvalue_male > 0.05 ~ "Female only",
  qvalue_male <= 0.05 & qvalue_female > 0.05 ~ "Male only",
  qvalue_female <= 0.05 & qvalue_male <= 0.05 ~ "Both",
  TRUE ~ "Not Significant"
)
  )

p_sex <- ggplot(merged_sex, aes(x = log_male, y = log_female)) +
  geom_point(aes(color = sig), alpha = 0.6, size = 2) +
 scale_color_manual(values = c(
  "Female only" = "red",
  "Male only" = "blue",
  "Both" = "purple",
  "Not Significant" = "grey80"
)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey30", linewidth = 0.7) +
  geom_text_repel(
    data = subset(merged_sex, !is.na(label_combined)),
    aes(label = label_combined),
    color = subset(merged_sex, !is.na(label_combined))$label_color,  
    size = 3,
    nudge_y = 0,
    direction = "both",
    box.padding = 0.5,
    point.padding = 0.5,
    max.overlaps = 5,
    segment.color = "grey50",
    force = 2,  
    bg.color = "white",  
    bg.r = 0.15  
  ) +
  geom_hline(yintercept = log10(0.05), linetype = "dotted", color = "grey40") +
  geom_vline(xintercept = log10(0.05), linetype = "dotted", color = "grey40") +
  coord_cartesian(xlim = c(-20, 0), ylim = c(-20, 0)) +
  labs(
    title = "All male vs All female Pathway Enrichment",
    x = "Male mean q-value (log10)",
    y = "Female mean q-value (log10)"
  ) +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

print(p_sex)
ggsave(
    filename = paste0("../invivo-pfas-immunotox/Eunnara stuff/sex.png", ".png"),
    plot     = p_sex,
    width    = 6, height = 5, dpi = 300,
    bg = "white"
  )
```
##PFAS
```{r}
pfos_df <- all_kegg %>% filter(PFAS == "PFOS")
pfoa_df <- all_kegg %>% filter(PFAS == "PFOA")

merged_pfas <- inner_join(
  pfos_df %>% group_by(Description) %>% summarize(qvalue_pfos = min(qvalue)),
  pfoa_df   %>% group_by(Description) %>% summarize(qvalue_pfoa = min(qvalue)),
  by = "Description"
) %>%
  mutate(
    log_pfos = log10(qvalue_pfos),
    log_pfoa   = log10(qvalue_pfoa),
    diff = log_pfos- log_pfoa
  )

# Near-diagonal
merged_pfas <- merged_pfas %>%
  mutate(label_near_diag = ifelse(abs(diff) < 0.5, Description, NA))

top_pfos <- merged_pfas %>%
  filter(qvalue_pfoa > 0.05) %>%
  arrange(qvalue_pfos) %>%
  slice_head(n = 2) %>%
  pull(Description)

merged_pfas <- merged_pfas %>%
  mutate(label_pfos_specific = ifelse(Description %in% top_pfos, Description, NA))

top_pfoa <- merged_pfas %>%
  filter(qvalue_pfos > 0.05) %>%
  arrange(qvalue_pfoa) %>%
  slice_head(n = 2) %>%
  pull(Description)

merged_pfas <- merged_pfas %>%
  mutate(label_pfoa_specific = ifelse(Description %in% top_pfoa, Description, NA))

# Top 5 shared 
shared_top5 <- merged_pfas %>%
  filter(qvalue_pfos <= 0.05, qvalue_pfoa <= 0.05) %>%
  mutate(mean_q = (qvalue_pfos + qvalue_pfoa) / 2) %>%
  arrange(mean_q) %>%
  slice_head(n = 5) %>%
  pull(Description)

merged_pfas <- merged_pfas %>%
  mutate(label_shared = ifelse(Description %in% shared_top5, Description, NA))

merged_pfas <- merged_pfas %>%
  mutate(
    label_combined = coalesce(
      label_shared,
      label_pfos_specific,
      label_pfoa_specific,
    ),
    label_color = case_when(
      !is.na(label_shared)          ~ "purple",
      !is.na(label_pfos_specific) ~ "red",
      !is.na(label_pfoa_specific)   ~ "blue",
      TRUE                          ~ "grey80"
    ),
      sig = case_when(
  qvalue_pfos<= 0.05 & qvalue_pfoa > 0.05 ~ "PFOS only",
  qvalue_pfoa <= 0.05 & qvalue_pfos > 0.05 ~ "PFOA only",
  qvalue_pfos <= 0.05 & qvalue_pfoa <= 0.05 ~ "Both",
  TRUE ~ "Not Significant"
)
  )

p_pfas <- ggplot(merged_pfas, aes(x = log_pfoa, y = log_pfos)) +
  geom_point(aes(color = sig), alpha = 0.6, size = 2) +
   scale_color_manual(values = c(
  "PFOS only" = "red",
  "PFOA only" = "blue",
  "Both" = "purple",
  "Not Significant" = "grey80"
)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey30", linewidth = 0.7) +
  geom_text_repel(
    data = subset(merged_pfas, !is.na(label_combined)),
    aes(label = label_combined),
    color = subset(merged_pfas, !is.na(label_combined))$label_color,
    size = 3,
    nudge_y = 0,
    direction = "both",
    box.padding = 0.5,
    point.padding = 0.5,
    max.overlaps = 10,
    segment.color = "grey50",
    force = 2,
    bg.color = "white",  
    bg.r = 0.15  
  ) +
  geom_hline(yintercept = log10(0.05), linetype = "dotted", color = "grey40") +
  geom_vline(xintercept = log10(0.05), linetype = "dotted", color = "grey40") +
  coord_cartesian(xlim = c(-20, 0), ylim = c(-20, 0)) +
  labs(
    title = "All PFOS vs All PFOA Pathway Enrichment",
    x = "pfoa mean q-value (log10)",
    y = "pfos mean q-value (log10)"
  ) +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

print(p_pfas)
  ggsave(
    filename = paste0("../invivo-pfas-immunotox/Eunnara stuff/pfas.png",  ".png"),
    plot     = p_pfas,
    width    = 6, height = 5, dpi = 300,
    bg = "white"
  )
```

